### PR TITLE
Fix default outputs in flake and update description

### PR DESCRIPTION
**Pull request by meain**
Format of flake output for defaults are a bit different with `flake-utils`. I've fixed that up in this PR. Also cleaned up a few other things in the flake file.

### CODE REVIEW

**Comment by peterldowns** [comment]
Hey @meain thanks for the PR. The description change is definitely appreciated. Can you please explain why the other changes are necessary, and what difference in behavior they lead to?

> Format of flake output for defaults are a bit different with flake-utils.

What do you mean by this?

**Comment by meain** [comment]
Ahh, my bad. Sorry for the rushed PR. As of now, if you try to run the app directly via a flake, you end up with this error. Same for shell.

```
nix run github:peterldowns/nix-search-cli
error: cannot find flake attribute 'github:peterldowns/nix-search-cli#defaultApp.x86_64-linux'

nix shell github:peterldowns/nix-search-cli
error: flake 'github:peterldowns/nix-search-cli' does not provide attribute 'packages.x86_64-linux.defaultPackage.x86_64-linux', 'legacyPackages.x86_64-linux.defaultPackage.x86_64-linux' or 'defaultPackage.x86_64-linux'
```

If you see [this](https://github.com/numtide/flake-utils#example) example in flake utils, you can see that we have to specify `defaultApp` instead of `default` inside `packages`.

```
nix run github:meain/nix-search-cli/fix-flake
search for packages via search.nixos.org

Usage:
  nix-search ...query [flags]
...
```

**Comment by peterldowns** [comment]
Thank you for the clearer explanation. Would you mind telling me what version of nix you're using? I cannot repro with nix 2.13.2. The [flakes wiki currently describes the schema as the way I'm using it](https://nixos.wiki/wiki/Flakes#Output_schema):

```nix
{
  # ...
  # Executed by `nix build .#<name>`
  packages."<system>"."<name>" = derivation;
  # Executed by `nix build .`
  packages."<system>".default = derivation;
  # Executed by `nix run .#<name>`
  apps."<system>"."<name>" = {
    type = "app";
    program = "<store-path>";
  };
  # Executed by `nix run . -- <args?>`
  apps."<system>".default = { type = "app"; program = "..."; };
  # ...
  # Used by `nix develop .#<name>`
  devShells."<system>"."<name>" = derivation;
  # Used by `nix develop`
  devShells."<system>".default = derivation;
  #...
}
```
If you're on a lower version of nix, probably there was a backwards-incompatible change in the flakes schema. If that's the case, I'll fix this by adding the `defaultPackage`, `defaultApp` and `defaultShell` attrs in addition to the current `apps.default` and `devShells.default` setup. And we can chalk this up to yet another case of the Nix project being poorly maintained, badly documented, broken by default, and user-unfriendly.

**Comment by peterldowns** [comment]
Suspicion confirmed -- here is the PR that updated the flake-utils example to use the "new" flake format, without updating the documentation or explaining when the flake format itself had been updated. 

https://github.com/numtide/flake-utils/pull/76

You know how you linked me the flake-utils readme earlier, https://github.com/numtide/flake-utils#example ? If you visit that, you'll see that the purported contents of the example flake file (as visible in the readme) are different than what's actually in the file. 😮‍💨

**Comment by meain** [comment]
Ahh, you are right. I was on a much older version of nix (`2.4`). I don't have this problem with the latest version. `fake-utils` mentioning `defaultPackage` kinda thew me off.

**Comment by meain** [comment]
It is cool if you just wanna close this as it not really an "issue".

**Comment by peterldowns** [comment]
@meain OK, I'll go ahead and close this PR. In https://github.com/peterldowns/nix-search-cli/commit/a080780286611a00e8ee51c2065d03050c2c76d8 I made two changes that should incorporate all the feedback you gave here:
- Updated the flake description
- Set 2.4-compatible attributes at the top level of the flake

Thank you again for opening the issue and helping me understand the problem you were having. Please let me know if you have any other feedback or advice.

**Pull request closed without merging**
